"""empty message

Revision ID: 20b5480eeb3a
Revises: 0ae13ee3ade6
Create Date: 2024-06-27 21:47:57.244345

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20b5480eeb3a"
down_revision: Union[str, None] = "0ae13ee3ade6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
