"""Add blocked field to Post model

Revision ID: 74fca43008eb
Revises: 20b5480eeb3a
Create Date: 2024-06-29 14:41:55.264341

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "74fca43008eb"
down_revision: Union[str, None] = "20b5480eeb3a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("blocked", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "blocked")
    # ### end Alembic commands ###
